import { OptimizationResult } from '../types/optimization';

export const defaultMockResult: OptimizationResult = {
  recommended_design: {
    rank: 1,
    category: 'Best Overall Solution',
    design: {
      name: 'Leh Winter Agricultural Shelter',
      length: 6.0,
      width: 4.0,
      height: 3.0,
      orientation: 180.0,
      wall_material_id: 'brick',
      wall_thickness: 0.23,
      roof_material_id: 'concrete',
      roof_thickness: 0.15,
      roof_type: 'sloped',
      floor_material_id: 'concrete',
      floor_thickness: 0.15,
      insulation_material_id: 'mineral_wool',
      insulation_thickness: 0.10,
      window_area: 4.0,
      window_orientation: 180.0,
      window_glazing_type: 'double_pane',
      door_area: 2.0,
      thermal_mass_kg: 1500.0,
      thermal_mass_material_id: 'stone',
      ach: 0.5,
    },
    simulation_result: {
      design: {
        length: 6.0, width: 4.0, height: 3.0, orientation: 180.0,
        wall_material_id: 'brick', wall_thickness: 0.23,
        roof_material_id: 'concrete', roof_thickness: 0.15, roof_type: 'sloped',
        floor_material_id: 'concrete', floor_thickness: 0.15,
        insulation_material_id: 'mineral_wool', insulation_thickness: 0.10,
        window_area: 4.0, window_orientation: 180.0, window_glazing_type: 'double_pane',
        door_area: 2.0, thermal_mass_kg: 1500.0, thermal_mass_material_id: 'stone', ach: 0.5
      },
      hourly: Array.from({ length: 24 }, (_, i) => ({
        hour: i,
        outside_temperature: -12.0 + Math.sin((i - 6) * (Math.PI / 12)) * 7.0,
        inside_temperature: 12.0 + Math.sin((i - 8) * (Math.PI / 12)) * 6.5,
        solar_radiation: i > 6 && i < 18 ? Math.sin((i - 6) * (Math.PI / 12)) * 650 : 0,
        solar_gain: i > 7 && i < 17 ? 1.8 : 0.1,
        wall_loss: 0.45,
        roof_loss: 0.35,
        floor_loss: 0.15,
        window_loss: 0.30,
        door_loss: 0.10,
        ventilation_loss: 0.25,
        net_heat: i > 7 && i < 17 ? 0.35 : -0.65,
      })),
      summary: {
        average_temperature: 17.8,
        min_temperature: 11.4,
        max_temperature: 24.1,
        comfort_hours: 19.2,
        total_simulation_hours: 24,
        comfort_percentage: 80.0,
        solar_gain_kwh: 10.4,
        heat_loss_kwh: 4.1,
        net_heat_kwh: 6.3,
        estimated_cost: 143000,
        thermal_score: 89.0,
        wall_u_value: 0.32,
        roof_u_value: 0.28,
        floor_area: 24.0,
        volume: 72.0,
        heat_loss_breakdown: {
          wall_kwh: 1.80,
          roof_kwh: 0.90,
          floor_kwh: 0.50,
          window_kwh: 0.70,
          door_kwh: 0.20,
          ventilation_kwh: 0.50,
        },
      },
    },
    why_explanation: [
      '✓ 10 cm Mineral Wool insulation significantly reduces wall conductive U-value to 0.32 W/m²K.',
      '✓ South-facing 4m² glazing maximizes daytime winter solar gain (10.4 kWh/day).',
      '✓ 1500 kg stone thermal mass stores daytime solar heat and dampens nighttime cooling.',
      '✓ Estimated construction cost ₹1,43,000 remains within budget limit (₹1,50,000).',
      '✓ Achieves 19.2 comfortable hours per day in Leh winter profile.',
    ],
  },
  top_designs: [],
  total_searched: 120,
  climate_location: 'Leh, Ladakh',
};

defaultMockResult.top_designs = [
  defaultMockResult.recommended_design,
  {
    rank: 2,
    category: 'Maximum Thermal Comfort',
    design: {
      ...defaultMockResult.recommended_design.design,
      name: 'High-Insulation Thermal Vault',
      insulation_thickness: 0.15,
      thermal_mass_kg: 3000.0,
    },
    simulation_result: {
      ...defaultMockResult.recommended_design.simulation_result,
      summary: {
        ...defaultMockResult.recommended_design.simulation_result.summary,
        comfort_hours: 21.5,
        comfort_percentage: 89.5,
        thermal_score: 94.0,
        estimated_cost: 149500,
      },
    },
    why_explanation: ['✓ 15 cm insulation and 3000 kg thermal mass provide near-constant indoor temperature.'],
  },
  {
    rank: 3,
    category: 'Lowest Construction Cost',
    design: {
      ...defaultMockResult.recommended_design.design,
      name: 'Low-Cost Adobe Passive Shelter',
      wall_material_id: 'adobe',
      insulation_thickness: 0.05,
    },
    simulation_result: {
      ...defaultMockResult.recommended_design.simulation_result,
      summary: {
        ...defaultMockResult.recommended_design.simulation_result.summary,
        comfort_hours: 15.0,
        comfort_percentage: 62.5,
        thermal_score: 76.0,
        estimated_cost: 95000,
      },
    },
    why_explanation: ['✓ Uses local mud/adobe block to minimize material freight cost while maintaining basic thermal performance.'],
  },
];
